// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXnGd6Nn210UPxdnVYA2VNtI8XKCYQOyI',
    appId: '1:426041654351:web:6139566749c8d1c087be3a',
    messagingSenderId: '426041654351',
    projectId: 'meditime-dc9b1',
    authDomain: 'meditime-dc9b1.firebaseapp.com',
    storageBucket: 'meditime-dc9b1.appspot.com',
    measurementId: 'G-5CFMB1W3HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9YKJ0ZC502wZjp5IzEGA51jKfJrIsLg',
    appId: '1:426041654351:android:8ed9ce3d391321dd87be3a',
    messagingSenderId: '426041654351',
    projectId: 'meditime-dc9b1',
    storageBucket: 'meditime-dc9b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqbHuwoluY-Ju8oSzdCtGfh-A05niUyc',
    appId: '1:426041654351:ios:610222a9d32fb7c087be3a',
    messagingSenderId: '426041654351',
    projectId: 'meditime-dc9b1',
    storageBucket: 'meditime-dc9b1.appspot.com',
    iosBundleId: 'com.example.meditime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqbHuwoluY-Ju8oSzdCtGfh-A05niUyc',
    appId: '1:426041654351:ios:610222a9d32fb7c087be3a',
    messagingSenderId: '426041654351',
    projectId: 'meditime-dc9b1',
    storageBucket: 'meditime-dc9b1.appspot.com',
    iosBundleId: 'com.example.meditime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXnGd6Nn210UPxdnVYA2VNtI8XKCYQOyI',
    appId: '1:426041654351:web:d0502e8e2a36082f87be3a',
    messagingSenderId: '426041654351',
    projectId: 'meditime-dc9b1',
    authDomain: 'meditime-dc9b1.firebaseapp.com',
    storageBucket: 'meditime-dc9b1.appspot.com',
    measurementId: 'G-9195QE6MXN',
  );
}
